### PR TITLE
fix: unit test Highlight Component

### PR DESCRIPTION
**Pull request by AnisTigrini**
@matthewwolfe Not too sure to understand the role of the children Prop in the highlight component.
Could we get rid of it or maybe keep it optionnal?

### CODE REVIEW

**Comment by matthewwolfe** [comment]
I think it could either be 

```jsx
<Highlight highlight={['test']}>This is just a test !</Highlight>
```

or 

```jsx
<Highlight highlight={['test']} text="This is just a test !" />
```

Do you have a preference?

**Comment by AnisTigrini** [comment]
In the first approach users could do soemthing like :
```
<Highlight highlight={['test']}><div>This is just a test</div></Highlight>
```
This would make the current code fail. So I think changing the **children** prop for **text** could be more straight forward for users.

**Comment by AnisTigrini** [comment]
Added unit testing for Link component.

**Comment by matthewwolfe** [comment]
Do you want to make the prop changes for children -> text in this PR or do you want me to do it separately?

**Comment by AnisTigrini** [comment]
Just did, sorry for the delay!

**Pull request merged**
